# Generated by Django 2.2.4 on 2019-08-29 07:19

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_readnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='readnum',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='readnum',
            name='readnum_for_date',
            field=models.IntegerField(default=0),
        ),
    ]
