# Generated by Django 2.2.4 on 2019-08-29 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190829_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readnum',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
