# Generated by Django 2.2.4 on 2019-08-29 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190829_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='date_time',
        ),
    ]
