# Generated by Django 2.2.4 on 2019-08-29 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_readnum_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='readnum_for_date',
        ),
    ]
