# Generated by Django 2.2.4 on 2019-08-29 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_readnum_readnum_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='readnum_date',
        ),
    ]
