# Generated by Django 2.2.4 on 2019-08-29 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_readnum_readnum_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='readnum',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
