# Generated by Django 2.2.4 on 2019-08-29 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_readnum_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadNumDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readnum_date', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='readnum',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='readnum',
            name='readnum_date',
        ),
    ]
