# Generated by Django 2.2.4 on 2019-08-30 02:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone 


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20190830_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='readnumdate',
            name='blog',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Blog'),
        ),
        migrations.AlterField(
            model_name='readnumdate',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
