# Generated by Django 2.2.4 on 2019-08-31 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20190830_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnumdate',
            name='blog',
        ),
    ]
