# Generated by Django 2.2.4 on 2019-08-31 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20190831_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readnumdate',
            options={'ordering': ['-date_time']},
        ),
        migrations.AlterField(
            model_name='readnumdate',
            name='date_time',
            field=models.DateTimeField(default=datetime.date(2019, 8, 31)),
        ),
    ]
