# Generated by Django 2.2.4 on 2019-08-31 07:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20190831_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readnumdate',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
