# Generated by Django 2.2.4 on 2019-09-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20190907_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='img_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
